# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import *
from PySide2.QtWidgets import *
from PySide2.QtGui import *
from VideoPlayer import *
from QEditText import *
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = ".\\platform\\"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 410)
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(680, 10, 101, 31))
        self.downloadButton.setObjectName("pushButton")
        self.linkEditTxt = MyQTextEdit(self.centralwidget)
        self.linkEditTxt.setGeometry(QtCore.QRect(10, 10, 501, 31))
        self.linkEditTxt.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(520, 10, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.videoPlayer = VideoPlayer(self.centralwidget)
        self.videoPlayer.setGeometry(QtCore.QRect(10, 40, 772, 340))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.setPlaceHolder()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Media Downloader"))
        MainWindow.setWindowIcon(QtGui.QIcon('.\\icon\\download_frame_icon.png'))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.downloadButton.setIcon(QtGui.QIcon('.\\icon\\download.png'))
        comboBoxList = ["Youtube","Facebook"]
        self.comboBox.addItems(comboBoxList)
        
    def setPlaceHolder(self):
        if(self.linkEditTxt.toPlainText() == ""):
            self.linkEditTxt.setText("Paste link here")
            self.linkEditTxt.setStyleSheet("QTextEdit {color:gray}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())